import os

FCG_DIR = os.path.dirname(os.path.realpath(__file__))
CACHE_DIR = FCG_DIR + '/cache'

ASSEMBLER_DIRS = [] 

SOURCE_DIRS = [] 
SOURCE_FILES_PREPROCESSED = False 

SPECIAL_MODULE_FILES = {}
EXCLUDE_MODULES = []

IGNORE_GLOBALS_FROM_MODULES = EXCLUDE_MODULES + [] 
IGNORE_DERIVED_TYPES = []
